# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'teckers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for teckers
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Alamofire', '~> 5.0.0-beta.5'

  target 'teckersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
